version: "3"
services:

    php:
        container_name: nuevogestor
        build: .
        image: repo.biblioetech.com/betandeal/nuevogestor:${VERSION}
        volumes:
            - ./pdfs:/var/www/Website/public/pdfs
            - .:/var/www/Website
            - ../logs:/var/log/apache2
        ports:
            - "8088:80"
        # links:
        #     - "mysql:db"
        environment:
            - VERSION=${VERSION}
            - APP_ENV=dev
            - APP_SECRET=1b0360fa702ad96cfcd9834632a467ad
            - DATABASE_URL=mysql://premiumpayuser:N_ashzob_9@pre.bdeal.pro:33060/ppay_symfony?serverVersion=5.7
            - DATABASE_URL_BD=mysql://preuser:N_ashzob_9@pre.bdeal.pro:33060/nuevoback?serverVersion=5.7
            - WKHTMLTOPDF_PATH=/usr/local/bin/wkhtmltopdf
            - WKHTMLTOIMAGE_PATH=/usr/local/bin/wkhtmltoimage
            - MAILER_URL=smtp://espimail.net:587?encryption=tls&auth_mode=login&username=biblioeteca@espimail.net&password=N_ashzob_9
            - MAILER_DSN=smtp://biblioeteca@espimail.net:N_ashzob_9@espimail.net:587
        restart: unless-stopped

    # mysql:
    #     container_name: premiumpay-mysql
    #     image: biblioeteca/mysql:5.7
    #     volumes:
    #         - ./db:/var/lib/mysql 
    #     # To avoid inteferences with existing mysql instances use 33060:3306
    #     ports:
    #         - "3306:3306"
    #     restart: unless-stopped
    https-portal:
        image: steveltn/https-portal:1
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./ssl_certs:/var/lib/https-portal
        environment:
            DOMAINS: 'bujaruelo.biblioeteca.net -> http://php #production' 

