<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CampaniasCodes extends \App\Entity\Main\CampaniasCodes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'idcasa', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'idcampania', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'project'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'idcasa', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'idcampania', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Main\\CampaniasCodes' . "\0" . 'project'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CampaniasCodes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcasa(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcasa', []);

        return parent::getIdcasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcasa(int $idcasa): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcasa', [$idcasa]);

        return parent::setIdcasa($idcasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcampania(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcampania', []);

        return parent::getIdcampania();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcampania(int $idcampania): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcampania', [$idcampania]);

        return parent::setIdcampania($idcampania);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(string $codigo): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(?int $idUsuario): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$idUsuario]);

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(?string $username): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', []);

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(bool $project): \App\Entity\Main\CampaniasCodes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', [$project]);

        return parent::setProject($project);
    }

}
