<?php

namespace Proxies\__CG__\App\Entity\Premiumpay;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DescuentoProducto extends \App\Entity\Premiumpay\DescuentoProducto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'iddescuentoProducto', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'porcentajeDescuento', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'maxUsos', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'utilizados', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'completados', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'idproducto'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'iddescuentoProducto', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'porcentajeDescuento', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'maxUsos', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'utilizados', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'completados', '' . "\0" . 'App\\Entity\\Premiumpay\\DescuentoProducto' . "\0" . 'idproducto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DescuentoProducto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIddescuentoProducto(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIddescuentoProducto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddescuentoProducto', []);

        return parent::getIddescuentoProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(?string $codigo): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeDescuento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeDescuento', []);

        return parent::getPorcentajeDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajeDescuento(?string $porcentajeDescuento): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajeDescuento', [$porcentajeDescuento]);

        return parent::setPorcentajeDescuento($porcentajeDescuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxUsos(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxUsos', []);

        return parent::getMaxUsos();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxUsos(?int $maxUsos): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxUsos', [$maxUsos]);

        return parent::setMaxUsos($maxUsos);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilizados(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilizados', []);

        return parent::getUtilizados();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilizados(?int $utilizados): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilizados', [$utilizados]);

        return parent::setUtilizados($utilizados);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompletados(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompletados', []);

        return parent::getCompletados();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompletados(?int $completados): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompletados', [$completados]);

        return parent::setCompletados($completados);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproducto(): ?\App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproducto', []);

        return parent::getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdproducto(?\App\Entity\Premiumpay\PasarelaBetandealProducto $idproducto): \App\Entity\Premiumpay\DescuentoProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdproducto', [$idproducto]);

        return parent::setIdproducto($idproducto);
    }

}
