<?php

namespace Proxies\__CG__\App\Entity\Old;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CampaniasEnlaces extends \App\Entity\Old\CampaniasEnlaces implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'idcampania', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'numeroEnlace', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'texto', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'urlInicial', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'activo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'idcampania', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'numeroEnlace', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'texto', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'urlInicial', '' . "\0" . 'App\\Entity\\Old\\CampaniasEnlaces' . "\0" . 'activo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CampaniasEnlaces $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcampania(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcampania', []);

        return parent::getIdcampania();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcampania(int $idcampania): \App\Entity\Old\CampaniasEnlaces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcampania', [$idcampania]);

        return parent::setIdcampania($idcampania);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroEnlace(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroEnlace', []);

        return parent::getNumeroEnlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroEnlace(int $numeroEnlace): \App\Entity\Old\CampaniasEnlaces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroEnlace', [$numeroEnlace]);

        return parent::setNumeroEnlace($numeroEnlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', []);

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto(string $texto): \App\Entity\Old\CampaniasEnlaces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', [$texto]);

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlInicial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlInicial', []);

        return parent::getUrlInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlInicial(string $urlInicial): \App\Entity\Old\CampaniasEnlaces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlInicial', [$urlInicial]);

        return parent::setUrlInicial($urlInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Old\CampaniasEnlaces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

}
