<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CampaniasCompetidores extends \App\Entity\Main\CampaniasCompetidores implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'casaBetandeal', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'campaniaBetandeal', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'casaCompetidora', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'cpa', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'cpaMoneda', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'rs', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'fee', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'feeMoneda', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'baseline'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'casaBetandeal', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'campaniaBetandeal', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'casaCompetidora', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'cpa', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'cpaMoneda', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'rs', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'fee', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'feeMoneda', '' . "\0" . 'App\\Entity\\Main\\CampaniasCompetidores' . "\0" . 'baseline'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CampaniasCompetidores $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasaBetandeal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasaBetandeal', []);

        return parent::getCasaBetandeal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasaBetandeal(?int $casaBetandeal): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasaBetandeal', [$casaBetandeal]);

        return parent::setCasaBetandeal($casaBetandeal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampaniaBetandeal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampaniaBetandeal', []);

        return parent::getCampaniaBetandeal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCampaniaBetandeal(?int $campaniaBetandeal): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampaniaBetandeal', [$campaniaBetandeal]);

        return parent::setCampaniaBetandeal($campaniaBetandeal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasaCompetidora(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasaCompetidora', []);

        return parent::getCasaCompetidora();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasaCompetidora(?int $casaCompetidora): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasaCompetidora', [$casaCompetidora]);

        return parent::setCasaCompetidora($casaCompetidora);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpa(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpa', []);

        return parent::getCpa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpa(?int $cpa): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpa', [$cpa]);

        return parent::setCpa($cpa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpaMoneda(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpaMoneda', []);

        return parent::getCpaMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpaMoneda(?string $cpaMoneda): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpaMoneda', [$cpaMoneda]);

        return parent::setCpaMoneda($cpaMoneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getRs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRs', []);

        return parent::getRs();
    }

    /**
     * {@inheritDoc}
     */
    public function setRs(?int $rs): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRs', [$rs]);

        return parent::setRs($rs);
    }

    /**
     * {@inheritDoc}
     */
    public function getFee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFee', []);

        return parent::getFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setFee(?int $fee): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFee', [$fee]);

        return parent::setFee($fee);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeeMoneda(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeeMoneda', []);

        return parent::getFeeMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeeMoneda(?string $feeMoneda): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeeMoneda', [$feeMoneda]);

        return parent::setFeeMoneda($feeMoneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseline(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseline', []);

        return parent::getBaseline();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseline(?string $baseline): \App\Entity\Main\CampaniasCompetidores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseline', [$baseline]);

        return parent::setBaseline($baseline);
    }

}
