<?php

namespace Proxies\__CG__\App\Entity\Ggms;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Campanias extends \App\Entity\Ggms\Campanias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'condiciones', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'comision', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'contenido', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'connectionApi', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'proyectos', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'casa', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'uriEnlaces', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'bonoGenerico', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'activo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'condiciones', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'comision', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'contenido', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'connectionApi', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'proyectos', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'casa', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'uriEnlaces', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'bonoGenerico', '' . "\0" . 'App\\Entity\\Ggms\\Campanias' . "\0" . 'activo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Campanias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondiciones(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondiciones', []);

        return parent::getCondiciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondiciones(string $condiciones): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondiciones', [$condiciones]);

        return parent::setCondiciones($condiciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getComision(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComision', []);

        return parent::getComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setComision(?string $comision): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComision', [$comision]);

        return parent::setComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', []);

        return parent::getContenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido(?string $contenido): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', [$contenido]);

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(string $tipo): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectionApi(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectionApi', []);

        return parent::getConnectionApi();
    }

    /**
     * {@inheritDoc}
     */
    public function setConnectionApi(string $connectionApi): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConnectionApi', [$connectionApi]);

        return parent::setConnectionApi($connectionApi);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectos(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectos', []);

        return parent::getProyectos();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectos(string $proyectos): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectos', [$proyectos]);

        return parent::setProyectos($proyectos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasa(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasa', []);

        return parent::getCasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasa(?int $casa): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasa', [$casa]);

        return parent::setCasa($casa);
    }

    /**
     * {@inheritDoc}
     */
    public function getUriEnlaces(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUriEnlaces', []);

        return parent::getUriEnlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setUriEnlaces(?string $uriEnlaces): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUriEnlaces', [$uriEnlaces]);

        return parent::setUriEnlaces($uriEnlaces);
    }

    /**
     * {@inheritDoc}
     */
    public function getBonoGenerico(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonoGenerico', []);

        return parent::getBonoGenerico();
    }

    /**
     * {@inheritDoc}
     */
    public function setBonoGenerico(?string $bonoGenerico): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBonoGenerico', [$bonoGenerico]);

        return parent::setBonoGenerico($bonoGenerico);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Ggms\Campanias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

}
