<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CampaniasEnlaceUsuario extends \App\Entity\Main\CampaniasEnlaceUsuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'idCampania', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'idCampaniaUsuario', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'tituloEnlace', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'urlPromocionada', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'numeroEnlace', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'activo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'idCampania', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'idCampaniaUsuario', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'tituloEnlace', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'urlPromocionada', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'numeroEnlace', '' . "\0" . 'App\\Entity\\Main\\CampaniasEnlaceUsuario' . "\0" . 'activo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CampaniasEnlaceUsuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(int $idUsuario): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$idUsuario]);

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCampania(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCampania', []);

        return parent::getIdCampania();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCampania(int $idCampania): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCampania', [$idCampania]);

        return parent::setIdCampania($idCampania);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCampaniaUsuario(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCampaniaUsuario', []);

        return parent::getIdCampaniaUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCampaniaUsuario(int $idCampaniaUsuario): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCampaniaUsuario', [$idCampaniaUsuario]);

        return parent::setIdCampaniaUsuario($idCampaniaUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloEnlace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloEnlace', []);

        return parent::getTituloEnlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloEnlace(string $tituloEnlace): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloEnlace', [$tituloEnlace]);

        return parent::setTituloEnlace($tituloEnlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlPromocionada(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlPromocionada', []);

        return parent::getUrlPromocionada();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlPromocionada(string $urlPromocionada): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlPromocionada', [$urlPromocionada]);

        return parent::setUrlPromocionada($urlPromocionada);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroEnlace(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroEnlace', []);

        return parent::getNumeroEnlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroEnlace(int $numeroEnlace): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroEnlace', [$numeroEnlace]);

        return parent::setNumeroEnlace($numeroEnlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Main\CampaniasEnlaceUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

}
