<?php

namespace Proxies\__CG__\App\Entity\Premiumpay;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PasarelaBetandealProducto extends \App\Entity\Premiumpay\PasarelaBetandealProducto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'idproducto', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'idpasarela', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'precioCop', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'moneda', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'enlace', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'tipster', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'emailtipster', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'emailcomprador', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'devoluciones', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'imagenFilename'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'idproducto', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'idpasarela', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'precioCop', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'moneda', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'enlace', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'tipster', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'emailtipster', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'emailcomprador', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'devoluciones', '' . "\0" . 'App\\Entity\\Premiumpay\\PasarelaBetandealProducto' . "\0" . 'imagenFilename'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PasarelaBetandealProducto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdproducto(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdproducto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproducto', []);

        return parent::getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpasarela(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpasarela', []);

        return parent::getIdpasarela();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpasarela(?int $idpasarela): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpasarela', [$idpasarela]);

        return parent::setIdpasarela($idpasarela);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(?string $descripcion): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio(?string $precio): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioCop(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioCop', []);

        return parent::getPrecioCop();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioCop(?string $precioCop): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioCop', [$precioCop]);

        return parent::setPrecioCop($precioCop);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', []);

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda(string $moneda): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', [$moneda]);

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnlace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnlace', []);

        return parent::getEnlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnlace(?string $enlace): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnlace', [$enlace]);

        return parent::setEnlace($enlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipster(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipster', []);

        return parent::getTipster();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipster(?string $tipster): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipster', [$tipster]);

        return parent::setTipster($tipster);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailtipster(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailtipster', []);

        return parent::getEmailtipster();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailtipster(?string $emailtipster): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailtipster', [$emailtipster]);

        return parent::setEmailtipster($emailtipster);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailcomprador(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailcomprador', []);

        return parent::getEmailcomprador();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailcomprador(?string $emailcomprador): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailcomprador', [$emailcomprador]);

        return parent::setEmailcomprador($emailcomprador);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevoluciones(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevoluciones', []);

        return parent::getDevoluciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevoluciones(bool $devoluciones): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevoluciones', [$devoluciones]);

        return parent::setDevoluciones($devoluciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenFilename', []);

        return parent::getImagenFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenFilename(?string $imagenFilename): \App\Entity\Premiumpay\PasarelaBetandealProducto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenFilename', [$imagenFilename]);

        return parent::setImagenFilename($imagenFilename);
    }

}
