<?php

namespace Proxies\__CG__\App\Entity\Old;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CampaniasUsuarioClicks extends \App\Entity\Old\CampaniasUsuarioClicks implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'idCampania', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'ip', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'fechaUltimoClick', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'clicksTotalesCampaniaUsuario', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'clicksUnicosCampaniaUsuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'idCampania', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'ip', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'fechaUltimoClick', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'clicksTotalesCampaniaUsuario', '' . "\0" . 'App\\Entity\\Old\\CampaniasUsuarioClicks' . "\0" . 'clicksUnicosCampaniaUsuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CampaniasUsuarioClicks $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCampania(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCampania', []);

        return parent::getIdCampania();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCampania(int $idCampania): \App\Entity\Old\CampaniasUsuarioClicks
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCampania', [$idCampania]);

        return parent::setIdCampania($idCampania);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', []);

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp(string $ip): \App\Entity\Old\CampaniasUsuarioClicks
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', [$ip]);

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\Old\CampaniasUsuarioClicks
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaUltimoClick(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaUltimoClick', []);

        return parent::getFechaUltimoClick();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaUltimoClick(?\DateTimeInterface $fechaUltimoClick): \App\Entity\Old\CampaniasUsuarioClicks
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaUltimoClick', [$fechaUltimoClick]);

        return parent::setFechaUltimoClick($fechaUltimoClick);
    }

    /**
     * {@inheritDoc}
     */
    public function getClicksTotalesCampaniaUsuario(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClicksTotalesCampaniaUsuario', []);

        return parent::getClicksTotalesCampaniaUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setClicksTotalesCampaniaUsuario(int $clicksTotalesCampaniaUsuario): \App\Entity\Old\CampaniasUsuarioClicks
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClicksTotalesCampaniaUsuario', [$clicksTotalesCampaniaUsuario]);

        return parent::setClicksTotalesCampaniaUsuario($clicksTotalesCampaniaUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getClicksUnicosCampaniaUsuario(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClicksUnicosCampaniaUsuario', []);

        return parent::getClicksUnicosCampaniaUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setClicksUnicosCampaniaUsuario(int $clicksUnicosCampaniaUsuario): \App\Entity\Old\CampaniasUsuarioClicks
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClicksUnicosCampaniaUsuario', [$clicksUnicosCampaniaUsuario]);

        return parent::setClicksUnicosCampaniaUsuario($clicksUnicosCampaniaUsuario);
    }

}
