<?php

namespace Proxies\__CG__\App\Entity\Premiumpay;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MovimientoSaldo extends \App\Entity\Premiumpay\MovimientoSaldo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'idmovimientoSaldo', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'importe', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'devolucion', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'timestamp', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'liberado', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'prepaymentIdtransaccion', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'paymentIdtransaccion', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'iduserPremiumpay'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'idmovimientoSaldo', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'importe', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'devolucion', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'timestamp', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'liberado', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'prepaymentIdtransaccion', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'paymentIdtransaccion', '' . "\0" . 'App\\Entity\\Premiumpay\\MovimientoSaldo' . "\0" . 'iduserPremiumpay'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MovimientoSaldo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdmovimientoSaldo(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmovimientoSaldo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmovimientoSaldo', []);

        return parent::getIdmovimientoSaldo();
    }

    /**
     * {@inheritDoc}
     */
    public function getImporte(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporte', []);

        return parent::getImporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporte(?string $importe): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporte', [$importe]);

        return parent::setImporte($importe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevolucion(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevolucion', []);

        return parent::getDevolucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevolucion(?bool $devolucion): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevolucion', [$devolucion]);

        return parent::setDevolucion($devolucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', []);

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp(\DateTimeInterface $timestamp): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', [$timestamp]);

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getLiberado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiberado', []);

        return parent::getLiberado();
    }

    /**
     * {@inheritDoc}
     */
    public function setLiberado(?bool $liberado): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLiberado', [$liberado]);

        return parent::setLiberado($liberado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaymentIdtransaccion(): ?\App\Entity\Premiumpay\PasarelaBetandealPrepaymentdata
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaymentIdtransaccion', []);

        return parent::getPrepaymentIdtransaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaymentIdtransaccion(?\App\Entity\Premiumpay\PasarelaBetandealPrepaymentdata $prepaymentIdtransaccion): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaymentIdtransaccion', [$prepaymentIdtransaccion]);

        return parent::setPrepaymentIdtransaccion($prepaymentIdtransaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentIdtransaccion(): ?\App\Entity\Premiumpay\PasarelaBetandealPaymentdata
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentIdtransaccion', []);

        return parent::getPaymentIdtransaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentIdtransaccion(?\App\Entity\Premiumpay\PasarelaBetandealPaymentdata $paymentIdtransaccion): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentIdtransaccion', [$paymentIdtransaccion]);

        return parent::setPaymentIdtransaccion($paymentIdtransaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduserPremiumpay(): ?\App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduserPremiumpay', []);

        return parent::getIduserPremiumpay();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduserPremiumpay(?\App\Entity\Premiumpay\UserPremiumpay $iduserPremiumpay): \App\Entity\Premiumpay\MovimientoSaldo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduserPremiumpay', [$iduserPremiumpay]);

        return parent::setIduserPremiumpay($iduserPremiumpay);
    }

}
