<?php

namespace Proxies\__CG__\App\Entity\Premiumpay;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tarjetas extends \App\Entity\Premiumpay\Tarjetas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'cvv', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'expired', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'tarjetadefecto', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'txnid', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'idUsuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'cvv', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'expired', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'tarjetadefecto', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'txnid', '' . "\0" . 'App\\Entity\\Premiumpay\\Tarjetas' . "\0" . 'idUsuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tarjetas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(?string $numero): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvv(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvv', []);

        return parent::getCvv();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvv(?int $cvv): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvv', [$cvv]);

        return parent::setCvv($cvv);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpired(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpired', []);

        return parent::getExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired(?\DateTimeInterface $expired): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', [$expired]);

        return parent::setExpired($expired);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(int $activo): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarjetadefecto(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarjetadefecto', []);

        return parent::getTarjetadefecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarjetadefecto(int $tarjetadefecto): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarjetadefecto', [$tarjetadefecto]);

        return parent::setTarjetadefecto($tarjetadefecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken(string $token): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnid', []);

        return parent::getTxnid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnid(string $txnid): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnid', [$txnid]);

        return parent::setTxnid($txnid);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario(): ?\App\Entity\Premiumpay\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(?\App\Entity\Premiumpay\User $idUsuario): \App\Entity\Premiumpay\Tarjetas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$idUsuario]);

        return parent::setIdUsuario($idUsuario);
    }

}
