<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuariosAfiliadosPagos extends \App\Entity\Main\UsuariosAfiliadosPagos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'idAfilPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'idUserAfiliado', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'fechaPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'jugadores', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'importePago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'idPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'estadoPago'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'idAfilPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'idUserAfiliado', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'fechaPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'jugadores', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'importePago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'idPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagos' . "\0" . 'estadoPago'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuariosAfiliadosPagos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAfilPago(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAfilPago();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAfilPago', []);

        return parent::getIdAfilPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserAfiliado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserAfiliado', []);

        return parent::getIdUserAfiliado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserAfiliado(int $idUserAfiliado): \App\Entity\Main\UsuariosAfiliadosPagos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserAfiliado', [$idUserAfiliado]);

        return parent::setIdUserAfiliado($idUserAfiliado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPago(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPago', []);

        return parent::getFechaPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPago(\DateTimeInterface $fechaPago): \App\Entity\Main\UsuariosAfiliadosPagos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPago', [$fechaPago]);

        return parent::setFechaPago($fechaPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getJugadores(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJugadores', []);

        return parent::getJugadores();
    }

    /**
     * {@inheritDoc}
     */
    public function setJugadores(int $jugadores): \App\Entity\Main\UsuariosAfiliadosPagos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJugadores', [$jugadores]);

        return parent::setJugadores($jugadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getImportePago(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportePago', []);

        return parent::getImportePago();
    }

    /**
     * {@inheritDoc}
     */
    public function setImportePago(float $importePago): \App\Entity\Main\UsuariosAfiliadosPagos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportePago', [$importePago]);

        return parent::setImportePago($importePago);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPago(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPago', []);

        return parent::getIdPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPago(int $idPago): \App\Entity\Main\UsuariosAfiliadosPagos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPago', [$idPago]);

        return parent::setIdPago($idPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoPago(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoPago', []);

        return parent::getEstadoPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoPago(bool $estadoPago): \App\Entity\Main\UsuariosAfiliadosPagos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoPago', [$estadoPago]);

        return parent::setEstadoPago($estadoPago);
    }

}
