<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoginAdmin extends \App\Entity\Main\LoginAdmin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'passwordId', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'plainpassword', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'nivelUser', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'responsable', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'lang', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'ultimoacceso', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'myip', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'esResponsable', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'activo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'passwordId', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'plainpassword', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'nivelUser', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'responsable', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'lang', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'ultimoacceso', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'myip', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'esResponsable', '' . "\0" . 'App\\Entity\\Main\\LoginAdmin' . "\0" . 'activo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LoginAdmin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(string $user): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordId', []);

        return parent::getPasswordId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordId(string $passwordId): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordId', [$passwordId]);

        return parent::setPasswordId($passwordId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainpassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainpassword', []);

        return parent::getPlainpassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainpassword(?string $plainpassword): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainpassword', [$plainpassword]);

        return parent::setPlainpassword($plainpassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(?string $password): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelUser(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelUser', []);

        return parent::getNivelUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelUser(?bool $nivelUser): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelUser', [$nivelUser]);

        return parent::setNivelUser($nivelUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(string $roles): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable(?int $responsable): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getLang(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLang', []);

        return parent::getLang();
    }

    /**
     * {@inheritDoc}
     */
    public function setLang(string $lang): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLang', [$lang]);

        return parent::setLang($lang);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(?string $telefono): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimoacceso(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimoacceso', []);

        return parent::getUltimoacceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoacceso(?\DateTimeInterface $ultimoacceso): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoacceso', [$ultimoacceso]);

        return parent::setUltimoacceso($ultimoacceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getMyip(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMyip', []);

        return parent::getMyip();
    }

    /**
     * {@inheritDoc}
     */
    public function setMyip(?string $myip): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMyip', [$myip]);

        return parent::setMyip($myip);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsResponsable(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsResponsable', []);

        return parent::getEsResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsResponsable(int $esResponsable): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsResponsable', [$esResponsable]);

        return parent::setEsResponsable($esResponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(bool $activo): \App\Entity\Main\LoginAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

}
