<?php

namespace Proxies\__CG__\App\Entity\Premiumpay;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TokenTarjeta extends \App\Entity\Premiumpay\TokenTarjeta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'idtokenTarjeta', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'cardnumber', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'expiry', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'cardBrand', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'cofTxnid', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'preferida', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'tsRegistered', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'userPremiumpayIduserPremiumpay'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'idtokenTarjeta', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'cardnumber', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'expiry', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'cardBrand', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'cofTxnid', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'preferida', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'activo', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'tsRegistered', '' . "\0" . 'App\\Entity\\Premiumpay\\TokenTarjeta' . "\0" . 'userPremiumpayIduserPremiumpay'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TokenTarjeta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdtokenTarjeta(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtokenTarjeta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtokenTarjeta', []);

        return parent::getIdtokenTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function getCardnumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardnumber', []);

        return parent::getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardnumber(?string $cardnumber): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardnumber', [$cardnumber]);

        return parent::setCardnumber($cardnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken(?string $token): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiry', []);

        return parent::getExpiry();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiry(?string $expiry): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiry', [$expiry]);

        return parent::setExpiry($expiry);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardBrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardBrand', []);

        return parent::getCardBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardBrand(?string $cardBrand): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardBrand', [$cardBrand]);

        return parent::setCardBrand($cardBrand);
    }

    /**
     * {@inheritDoc}
     */
    public function getCofTxnid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCofTxnid', []);

        return parent::getCofTxnid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCofTxnid(?string $cofTxnid): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCofTxnid', [$cofTxnid]);

        return parent::setCofTxnid($cofTxnid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferida(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferida', []);

        return parent::getPreferida();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferida(?bool $preferida): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferida', [$preferida]);

        return parent::setPreferida($preferida);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo(?bool $activo): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTsRegistered(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTsRegistered', []);

        return parent::getTsRegistered();
    }

    /**
     * {@inheritDoc}
     */
    public function setTsRegistered(?\DateTimeInterface $tsRegistered): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTsRegistered', [$tsRegistered]);

        return parent::setTsRegistered($tsRegistered);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPremiumpayIduserPremiumpay(): ?\App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPremiumpayIduserPremiumpay', []);

        return parent::getUserPremiumpayIduserPremiumpay();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPremiumpayIduserPremiumpay(?\App\Entity\Premiumpay\UserPremiumpay $userPremiumpayIduserPremiumpay): \App\Entity\Premiumpay\TokenTarjeta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPremiumpayIduserPremiumpay', [$userPremiumpayIduserPremiumpay]);

        return parent::setUserPremiumpayIduserPremiumpay($userPremiumpayIduserPremiumpay);
    }

}
