<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuariosAfiliadosPagosPremium extends \App\Entity\Main\UsuariosAfiliadosPagosPremium implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'idPremPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'idtipster', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'datepayment', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'product', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'payment', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'quantity', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'comision', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'importePago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'estadoPago'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'idPremPago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'idtipster', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'datepayment', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'product', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'payment', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'quantity', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'comision', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'importePago', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosPagosPremium' . "\0" . 'estadoPago'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuariosAfiliadosPagosPremium $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPremPago(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPremPago();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPremPago', []);

        return parent::getIdPremPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipster(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipster', []);

        return parent::getIdtipster();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipster(int $idtipster): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipster', [$idtipster]);

        return parent::setIdtipster($idtipster);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatepayment(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatepayment', []);

        return parent::getDatepayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatepayment(\DateTimeInterface $datepayment): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatepayment', [$datepayment]);

        return parent::setDatepayment($datepayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(string $product): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$product]);

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayment(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayment', []);

        return parent::getPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayment(string $payment): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayment', [$payment]);

        return parent::setPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity(float $quantity): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getComision(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComision', []);

        return parent::getComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setComision(float $comision): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComision', [$comision]);

        return parent::setComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function getImportePago(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportePago', []);

        return parent::getImportePago();
    }

    /**
     * {@inheritDoc}
     */
    public function setImportePago(float $importePago): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportePago', [$importePago]);

        return parent::setImportePago($importePago);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoPago(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoPago', []);

        return parent::getEstadoPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoPago(bool $estadoPago): \App\Entity\Main\UsuariosAfiliadosPagosPremium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoPago', [$estadoPago]);

        return parent::setEstadoPago($estadoPago);
    }

}
