<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Noticias extends \App\Entity\Main\Noticias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'idNoticia', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenido', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloEn', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoEn', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloDe', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoDe', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloFr', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoFr', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloIt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoIt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloPt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoPt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'idCasPais', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'actnoticia'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'idNoticia', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenido', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloEn', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoEn', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloDe', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoDe', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloFr', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoFr', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloIt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoIt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'tituloPt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'contenidoPt', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'idCasPais', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Main\\Noticias' . "\0" . 'actnoticia'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Noticias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdNoticia(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdNoticia();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNoticia', []);

        return parent::getIdNoticia();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(string $fecha): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', []);

        return parent::getContenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido(string $contenido): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', [$contenido]);

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloEn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloEn', []);

        return parent::getTituloEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloEn(string $tituloEn): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloEn', [$tituloEn]);

        return parent::setTituloEn($tituloEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoEn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoEn', []);

        return parent::getContenidoEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoEn(string $contenidoEn): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoEn', [$contenidoEn]);

        return parent::setContenidoEn($contenidoEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloDe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloDe', []);

        return parent::getTituloDe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloDe(string $tituloDe): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloDe', [$tituloDe]);

        return parent::setTituloDe($tituloDe);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoDe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoDe', []);

        return parent::getContenidoDe();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoDe(string $contenidoDe): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoDe', [$contenidoDe]);

        return parent::setContenidoDe($contenidoDe);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloFr', []);

        return parent::getTituloFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloFr(string $tituloFr): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloFr', [$tituloFr]);

        return parent::setTituloFr($tituloFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoFr', []);

        return parent::getContenidoFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoFr(string $contenidoFr): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoFr', [$contenidoFr]);

        return parent::setContenidoFr($contenidoFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloIt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloIt', []);

        return parent::getTituloIt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloIt(string $tituloIt): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloIt', [$tituloIt]);

        return parent::setTituloIt($tituloIt);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoIt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoIt', []);

        return parent::getContenidoIt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoIt(string $contenidoIt): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoIt', [$contenidoIt]);

        return parent::setContenidoIt($contenidoIt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloPt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloPt', []);

        return parent::getTituloPt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloPt(string $tituloPt): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloPt', [$tituloPt]);

        return parent::setTituloPt($tituloPt);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoPt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoPt', []);

        return parent::getContenidoPt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoPt(string $contenidoPt): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoPt', [$contenidoPt]);

        return parent::setContenidoPt($contenidoPt);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCasPais(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCasPais', []);

        return parent::getIdCasPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCasPais(?bool $idCasPais): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCasPais', [$idCasPais]);

        return parent::setIdCasPais($idCasPais);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen(?string $imagen): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getActnoticia(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActnoticia', []);

        return parent::getActnoticia();
    }

    /**
     * {@inheritDoc}
     */
    public function setActnoticia(bool $actnoticia): \App\Entity\Main\Noticias
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActnoticia', [$actnoticia]);

        return parent::setActnoticia($actnoticia);
    }

}
