<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EstadisticasApi extends \App\Entity\Main\EstadisticasApi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'subId', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'idCampaniaUsuario', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'fuenteMarketing', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'registros', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'depositantesPrimeraVez', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'cpaGenerados', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'connectionId', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'comisionGenerada', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'clicksUnicos', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'clicksTotales'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'subId', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'idCampaniaUsuario', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'fuenteMarketing', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'registros', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'depositantesPrimeraVez', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'cpaGenerados', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'connectionId', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'comisionGenerada', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'clicksUnicos', '' . "\0" . 'App\\Entity\\Main\\EstadisticasApi' . "\0" . 'clicksTotales'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EstadisticasApi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubId', []);

        return parent::getSubId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubId(?string $subId): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubId', [$subId]);

        return parent::setSubId($subId);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCampaniaUsuario(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCampaniaUsuario', []);

        return parent::getIdCampaniaUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCampaniaUsuario(int $idCampaniaUsuario): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCampaniaUsuario', [$idCampaniaUsuario]);

        return parent::setIdCampaniaUsuario($idCampaniaUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuenteMarketing(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuenteMarketing', []);

        return parent::getFuenteMarketing();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuenteMarketing(string $fuenteMarketing): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuenteMarketing', [$fuenteMarketing]);

        return parent::setFuenteMarketing($fuenteMarketing);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistros(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistros', []);

        return parent::getRegistros();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistros(int $registros): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistros', [$registros]);

        return parent::setRegistros($registros);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositantesPrimeraVez(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositantesPrimeraVez', []);

        return parent::getDepositantesPrimeraVez();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositantesPrimeraVez(int $depositantesPrimeraVez): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositantesPrimeraVez', [$depositantesPrimeraVez]);

        return parent::setDepositantesPrimeraVez($depositantesPrimeraVez);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpaGenerados(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpaGenerados', []);

        return parent::getCpaGenerados();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpaGenerados(int $cpaGenerados): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpaGenerados', [$cpaGenerados]);

        return parent::setCpaGenerados($cpaGenerados);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectionId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectionId', []);

        return parent::getConnectionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setConnectionId(string $connectionId): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConnectionId', [$connectionId]);

        return parent::setConnectionId($connectionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getComisionGenerada(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComisionGenerada', []);

        return parent::getComisionGenerada();
    }

    /**
     * {@inheritDoc}
     */
    public function setComisionGenerada(float $comisionGenerada): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComisionGenerada', [$comisionGenerada]);

        return parent::setComisionGenerada($comisionGenerada);
    }

    /**
     * {@inheritDoc}
     */
    public function getClicksUnicos(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClicksUnicos', []);

        return parent::getClicksUnicos();
    }

    /**
     * {@inheritDoc}
     */
    public function setClicksUnicos(?int $clicksUnicos): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClicksUnicos', [$clicksUnicos]);

        return parent::setClicksUnicos($clicksUnicos);
    }

    /**
     * {@inheritDoc}
     */
    public function getClicksTotales(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClicksTotales', []);

        return parent::getClicksTotales();
    }

    /**
     * {@inheritDoc}
     */
    public function setClicksTotales(?int $clicksTotales): \App\Entity\Main\EstadisticasApi
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClicksTotales', [$clicksTotales]);

        return parent::setClicksTotales($clicksTotales);
    }

}
