<?php

namespace Proxies\__CG__\App\Entity\Main;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuariosAfiliadosSuper extends \App\Entity\Main\UsuariosAfiliadosSuper implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'idCampBid', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'idCamp', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'textoEs', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'textoEn', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'urlInicial', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'urlMobile', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'bid', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'actactivo', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'actsport'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'idCampBid', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'idCamp', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'textoEs', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'textoEn', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'urlInicial', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'urlMobile', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'bid', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'actactivo', '' . "\0" . 'App\\Entity\\Main\\UsuariosAfiliadosSuper' . "\0" . 'actsport'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuariosAfiliadosSuper $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCampBid(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCampBid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCampBid', []);

        return parent::getIdCampBid();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCamp(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCamp', []);

        return parent::getIdCamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCamp(int $idCamp): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCamp', [$idCamp]);

        return parent::setIdCamp($idCamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoEs(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoEs', []);

        return parent::getTextoEs();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextoEs(?string $textoEs): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextoEs', [$textoEs]);

        return parent::setTextoEs($textoEs);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextoEn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextoEn', []);

        return parent::getTextoEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextoEn(?string $textoEn): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextoEn', [$textoEn]);

        return parent::setTextoEn($textoEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlInicial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlInicial', []);

        return parent::getUrlInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlInicial(?string $urlInicial): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlInicial', [$urlInicial]);

        return parent::setUrlInicial($urlInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlMobile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlMobile', []);

        return parent::getUrlMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlMobile(?string $urlMobile): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlMobile', [$urlMobile]);

        return parent::setUrlMobile($urlMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getBid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBid', []);

        return parent::getBid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBid(?string $bid): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBid', [$bid]);

        return parent::setBid($bid);
    }

    /**
     * {@inheritDoc}
     */
    public function getActactivo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActactivo', []);

        return parent::getActactivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setActactivo(bool $actactivo): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActactivo', [$actactivo]);

        return parent::setActactivo($actactivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActsport(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActsport', []);

        return parent::getActsport();
    }

    /**
     * {@inheritDoc}
     */
    public function setActsport(bool $actsport): \App\Entity\Main\UsuariosAfiliadosSuper
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActsport', [$actsport]);

        return parent::setActsport($actsport);
    }

}
