<?php

namespace Proxies\__CG__\App\Entity\Premiumpay;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserPremiumpay extends \App\Entity\Premiumpay\UserPremiumpay implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'iduserPremiumpay', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'recibirSpam', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'avatar', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'saldoActual', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'saldoRetenido', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'telefonoPrefijo', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'telefonoPaisIso', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'tsRegistered', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'imagenFilename', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'dtAceptaspam', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'repassToken', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'validationToken', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'impersonateToken'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'iduserPremiumpay', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'recibirSpam', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'avatar', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'saldoActual', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'saldoRetenido', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'telefonoPrefijo', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'telefonoPaisIso', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'tsRegistered', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'imagenFilename', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'dtAceptaspam', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'repassToken', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'validationToken', '' . "\0" . 'App\\Entity\\Premiumpay\\UserPremiumpay' . "\0" . 'impersonateToken'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserPremiumpay $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIduserPremiumpay(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIduserPremiumpay();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduserPremiumpay', []);

        return parent::getIduserPremiumpay();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(?string $password): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(?string $telefono): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento(?\DateTimeInterface $fechaNacimiento): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecibirSpam(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecibirSpam', []);

        return parent::getRecibirSpam();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecibirSpam(?bool $recibirSpam): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecibirSpam', [$recibirSpam]);

        return parent::setRecibirSpam($recibirSpam);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(?string $nombre): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar(?string $avatar): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', [$avatar]);

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldoActual(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldoActual', []);

        return parent::getSaldoActual();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaldoActual(?string $saldoActual): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaldoActual', [$saldoActual]);

        return parent::setSaldoActual($saldoActual);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldoRetenido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldoRetenido', []);

        return parent::getSaldoRetenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaldoRetenido(?string $saldoRetenido): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaldoRetenido', [$saldoRetenido]);

        return parent::setSaldoRetenido($saldoRetenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoPrefijo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoPrefijo', []);

        return parent::getTelefonoPrefijo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoPrefijo(?string $telefonoPrefijo): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoPrefijo', [$telefonoPrefijo]);

        return parent::setTelefonoPrefijo($telefonoPrefijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoPaisIso(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoPaisIso', []);

        return parent::getTelefonoPaisIso();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoPaisIso(?string $telefonoPaisIso): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoPaisIso', [$telefonoPaisIso]);

        return parent::setTelefonoPaisIso($telefonoPaisIso);
    }

    /**
     * {@inheritDoc}
     */
    public function getTsRegistered(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTsRegistered', []);

        return parent::getTsRegistered();
    }

    /**
     * {@inheritDoc}
     */
    public function setTsRegistered(?\DateTimeInterface $tsRegistered): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTsRegistered', [$tsRegistered]);

        return parent::setTsRegistered($tsRegistered);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenFilename', []);

        return parent::getImagenFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenFilename(?string $imagenFilename): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenFilename', [$imagenFilename]);

        return parent::setImagenFilename($imagenFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtAceptaspam(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtAceptaspam', []);

        return parent::getDtAceptaspam();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtAceptaspam(?\DateTimeInterface $dtAceptaspam): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtAceptaspam', [$dtAceptaspam]);

        return parent::setDtAceptaspam($dtAceptaspam);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepassToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepassToken', []);

        return parent::getRepassToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepassToken(?string $repassToken): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepassToken', [$repassToken]);

        return parent::setRepassToken($repassToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationToken', []);

        return parent::getValidationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidationToken(?string $validationToken): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidationToken', [$validationToken]);

        return parent::setValidationToken($validationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpersonateToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpersonateToken', []);

        return parent::getImpersonateToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpersonateToken(?string $impersonateToken): \App\Entity\Premiumpay\UserPremiumpay
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpersonateToken', [$impersonateToken]);

        return parent::setImpersonateToken($impersonateToken);
    }

}
