<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUry339e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUry339e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUry339e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUry339e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUry339e\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ury339e',
    'container.build_id' => '0f062d63',
    'container.build_time' => 1649843484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUry339e');
