<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7R2JuWG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7R2JuWG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7R2JuWG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7R2JuWG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7R2JuWG\App_KernelDevDebugContainer([
    'container.build_hash' => '7R2JuWG',
    'container.build_id' => '9d88ea18',
    'container.build_time' => 1652174084,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7R2JuWG');
