<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2CVvSv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2CVvSv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ2CVvSv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ2CVvSv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ2CVvSv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q2CVvSv',
    'container.build_id' => 'cd976616',
    'container.build_time' => 1652270781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2CVvSv');
